### ISSUE TITLE
[Todo] 07/29 토

### ISSUE THREAD

**Issue by 0gunkim** [mi-gan-zi/FE-MiGanZi#105]
24일 🚀 Todo #78 

### pang

- [x]  태그 

- [ ] 닉네임 중복검사 (with. max)

- [x] vercel max 이름 이슈 (협업한느데 문제가 없어서 일단 킵)

### yarn

- [x] 플레이를 재생시키고 뒤로가기 했을 때 계속 재생되는 이슈 
- [x] 플레이 UI(레코드 테두리) 개선 
- [x] pang말한 Enter key로 댓글 작성 개선

- [x] 디테일 페이지 들어갔을 때 스크롤이 상단으로 위치하는 로직 추가
- [x] 스크롤이 상단으로 가는 로직을 커스텀 훅으로 제작하기

- [x] 토큰이 없을 때 디테일 페이지 데이터가 조회 되지 않은 현상 (react-query로 리펙터링 한 이후터 이슈 발생 )
- [x] 토큰이 없을 때 깨지는 UI(플레이리스트) 확인하기

### max
- [x] 생성페이지 상태관리
~~- [ ] 페이지 이동 인가 로직 다시 만들고 테스트하기~~
- [x] 이미지세션에서 뒤로가기 했을 때 이미지 데이터 초기화(이전에는 이미지 선택하고 뒤로갔다가 다시 이미지 세션으로 가게 되면 이미지 데이터가 남아 있었음)
- [x] 게시글 작성 인가
~~- [ ] 댓글 작성 인가 (router 에서 프롭스로 전달)~~
