### ISSUE TITLE
[Todo] 7/24 토요일(중간점검)까지

### ISSUE THREAD

**Issue by 0gunkim** [mi-gan-zi/FE-MiGanZi#78]
### yarn
    
- [ ]  버그 잡기 → react-query를 이용해서 post 버튼 연타 막기
- [ ] #97
- [x]  플레이 리스트 UI 수정 → 검정 테두리

    
### susu
- [ ] 로그인/ 재로그인
- [x] **알림 뷰, 내가 쓴 댓글, 글 api요청**

    
### pangGu
~~UI 수정 → ratio~~
- [x] API수정
- [ ] 닉네임 중복검사 기능 추가
- [ ] 마이페이지 닉네임 변경할 때 중복 검사 버튼을 누르지 않고 자동으로(with max)
       
### max
- [x] 중복검사 인풋 디바운스 기능(with pangGu)
- [x] 카카오톡 위도 경도 쿼리에 넣기 지금은 없음
- [x] Axios 구체화
~~contextAPI~~
- [x] localrepo 모듈화
- [x] local expire 추가 로직 
--- 추가 7/26 ---
- [x] 로그아웃 토큰 이슈 #86 , #77 
- [ ] 생성페이지 상태관리 리펙터링
- [ ] 생성페이지 네이밍 수정

### 공통
- [ ] 전체적인 UI 레이아웃
- [ ] 팝업 뷰

**Comment by Goldenprevue** [comment]
로그아웃 토큰 이슈 https://github.com/mi-gan-zi/FE-MiGanZi/issues/86 , https://github.com/mi-gan-zi/FE-MiGanZi/issues/77

access가 만료되면  reissue 요청 및 업데이트 로직 추가 완료
